name: quote-box-zh_tw
author: Yu-huan Kuo <touch@rnmeow.com>
description: Get a quote to your GitHub Gist, API powered by Elegant TW.
runs:
  using: 'node20'
  main: 'dist/index.js'
input:
  file:
    description: "The file you would like to use (in JSON)"
    required: true
    default: "./quotes.json"  
branding:
  icon: 'file-text'
  color: 'yellow' 
